# Generated by Django 5.2.4 on 2026-02-02 20:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_active_course_updated_at_and_more'),
        ('results', '0002_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Компетенция')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('category', models.CharField(blank=True, max_length=120, verbose_name='Категория')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='CompetencyAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень (0-10)')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('assessed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата оценки')),
                ('assessor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competency_assessments_given', to=settings.AUTH_USER_MODEL, verbose_name='Оценил')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='users.competency', verbose_name='Компетенция')),
                ('task_submission', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.tasksubmission', verbose_name='Сдача задания')),
                ('test_result', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='results.testresult', verbose_name='Результат теста')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competency_assessments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Оценка компетенции',
                'verbose_name_plural': 'Оценки компетенций',
            },
        ),
        migrations.CreateModel(
            name='UserCompetency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Уровень (0-10)')),
                ('source', models.CharField(choices=[('MANAGER', 'Оценка менеджера'), ('TEST', 'Результаты тестов'), ('TASK', 'Практические задания'), ('SELF', 'Самооценка'), ('SYSTEM', 'Системная')], default='MANAGER', max_length=20, verbose_name='Источник')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('competency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_levels', to='users.competency', verbose_name='Компетенция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competencies', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Компетенция сотрудника',
                'verbose_name_plural': 'Компетенции сотрудников',
                'unique_together': {('user', 'competency')},
            },
        ),
    ]
