# Generated by Django 5.2.4 on 2026-02-07 00:00

from django.db import migrations, models


def add_default_specialty(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Specialty = apps.get_model('users', 'Specialty')

    missing = User.objects.filter(role='EMPLOYEE', specialty__isnull=True)
    if not missing.exists():
        return

    specialty, _ = Specialty.objects.get_or_create(
        name='Общая',
        defaults={'description': 'Общая специализация', 'is_active': True},
    )
    missing.update(specialty=specialty)


class Migration(migrations.Migration):
    # Need separate transactions: data fix first, then constraint.
    atomic = False

    dependencies = [
        ('users', '0004_specialty_user_specialty'),
    ]

    operations = [
        migrations.RunPython(add_default_specialty, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(
                check=(
                    models.Q(role='EMPLOYEE', specialty__isnull=False)
                    | ~models.Q(role='EMPLOYEE')
                ),
                name='user_employee_specialty_required',
            ),
        ),
    ]
