# Generated by Django 5.2.4 on 2026-02-07 00:00

import django.db.models.deletion
from django.db import migrations, models


def copy_positions(apps, schema_editor):
    User = apps.get_model('users', 'User')
    Position = apps.get_model('users', 'Position')

    users = User.objects.exclude(position__isnull=True).exclude(position='')
    for user in users:
        name = (user.position or '').strip()
        if not name:
            continue
        position = Position.objects.filter(name__iexact=name).first()
        if not position:
            position = Position.objects.create(name=name)
        user.position_ref = position
        user.save(update_fields=['position_ref'])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('users', '0005_user_employee_specialty_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Должность')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='position_ref',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='users',
                to='users.position',
                verbose_name='Должность',
            ),
        ),
        migrations.RunPython(copy_positions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='position',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='position_ref',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
