# Generated by Django 5.2.4 on 2026-02-07 00:00

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_position_user_position_fk_remove_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.UserManager()),
            ],
        ),
    ]
