# Generated by Django 5.2.4 on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='registration_review_comment',
            field=models.TextField(blank=True, verbose_name='Комментарий к решению'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата решения'),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_reviewed_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='registration_reviews',
                to='users.user',
                verbose_name='Решение принял',
            ),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_status',
            field=models.CharField(
                choices=[
                    ('PENDING', 'Ожидает подтверждения'),
                    ('APPROVED', 'Подтверждён'),
                    ('REJECTED', 'Отклонён'),
                ],
                default='APPROVED',
                max_length=20,
                verbose_name='Статус регистрации',
            ),
        ),
    ]

