# Generated by Django 5.2.4 on 2026-04-22

from django.db import migrations


CREATE_SQL = """
-- Ensure AuditLog inserts from DB functions do not violate NOT NULL user_agent.
ALTER TABLE IF EXISTS analytics_auditlog
    ALTER COLUMN user_agent SET DEFAULT '';

UPDATE analytics_auditlog
SET user_agent = ''
WHERE user_agent IS NULL;

CREATE OR REPLACE PROCEDURE sp_log_manual_event(
    p_user_id BIGINT,
    p_event_type VARCHAR(30),
    p_course_id BIGINT DEFAULT NULL,
    p_message TEXT DEFAULT NULL
)
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO analytics_trainingevent(user_id, event_type, course_id, created_at, metadata)
    VALUES (
        p_user_id,
        p_event_type,
        p_course_id,
        NOW(),
        jsonb_build_object('source', 'procedure', 'message', COALESCE(p_message, ''))
    );

    INSERT INTO analytics_auditlog(actor_id, action, object_type, object_id, message, metadata, ip_address, user_agent, created_at)
    VALUES (
        p_user_id,
        'MANUAL_EVENT_LOGGED',
        'TrainingEvent',
        '',
        COALESCE(p_message, 'Manual event logged'),
        jsonb_build_object('event_type', p_event_type, 'course_id', p_course_id),
        NULL,
        '',
        NOW()
    );
END;
$$;

CREATE OR REPLACE FUNCTION trg_testresult_audit_insert_fn()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $$
BEGIN
    INSERT INTO analytics_auditlog(actor_id, action, object_type, object_id, message, metadata, ip_address, user_agent, created_at)
    VALUES (
        NEW.user_id,
        'TEST_RESULT_CREATED',
        'TestResult',
        NEW.id::TEXT,
        'Создан новый результат теста',
        jsonb_build_object('test_id', NEW.test_id, 'status', NEW.status, 'score', NEW.score),
        NULL,
        '',
        NOW()
    );
    RETURN NEW;
END;
$$;
"""


def apply_sql(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    with schema_editor.connection.cursor() as cursor:
        cursor.execute(CREATE_SQL)


class Migration(migrations.Migration):
    dependencies = [
        ("analytics", "0003_db_objects_sql"),
    ]

    operations = [
        migrations.RunPython(apply_sql, reverse_code=migrations.RunPython.noop),
    ]

