# Generated by Django 5.2.4 on 2026-02-02 20:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_is_active_course_updated_at_and_more'),
        ('feedback', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('rating', models.IntegerField(blank=True, null=True, verbose_name='Оценка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_reviews_given', to=settings.AUTH_USER_MODEL, verbose_name='Менеджер')),
                ('task_submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='courses.tasksubmission', verbose_name='Сдача задания')),
            ],
            options={
                'verbose_name': 'Отзыв по заданию',
                'verbose_name_plural': 'Отзывы по заданиям',
            },
        ),
    ]
