# Generated by Django 5.2.4 on 2026-04-27 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_directmessageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='directchat',
            name='user1_last_read_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='directchat',
            name='user2_last_read_message_id',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
