# Generated by Django 5.2.4 on 2026-02-02 20:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='course',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата назначения'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Назначил'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок прохождения'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата начала'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Назначен'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершён'), ('OVERDUE', 'Просрочен'), ('CANCELLED', 'Отменён')], default='ASSIGNED', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.course', verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)'),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.CreateModel(
            name='CourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название материала')),
                ('material_type', models.CharField(choices=[('TEXT', 'Текст'), ('LINK', 'Ссылка'), ('FILE', 'Файл')], default='TEXT', max_length=10, verbose_name='Тип материала')),
                ('content', models.TextField(blank=True, verbose_name='Содержание')),
                ('url', models.URLField(blank=True, verbose_name='Ссылка')),
                ('file', models.FileField(blank=True, null=True, upload_to='course_materials/', verbose_name='Файл')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Материал курса',
                'verbose_name_plural': 'Материалы курсов',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название программы')),
                ('description', models.TextField(blank=True, verbose_name='Описание программы')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_programs', to=settings.AUTH_USER_MODEL, verbose_name='Создатель программы')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Описание задания')),
                ('criteria', models.TextField(blank=True, verbose_name='Критерии оценки')),
                ('task_type', models.CharField(choices=[('PRACTICAL', 'Практическое'), ('CASE', 'Кейс'), ('ESSAY', 'Эссе'), ('PROJECT', 'Проект')], default='PRACTICAL', max_length=20, verbose_name='Тип задания')),
                ('max_score', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный балл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='courses.course', verbose_name='Курс')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('program', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='courses.learningprogram', verbose_name='Программа')),
            ],
        ),
        migrations.CreateModel(
            name='TaskAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата назначения')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок выполнения')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Назначено'), ('IN_PROGRESS', 'В процессе'), ('SUBMITTED', 'Отправлено'), ('REVIEWED', 'Проверено'), ('RETURNED', 'Возвращено'), ('CANCELLED', 'Отменено')], default='ASSIGNED', max_length=20, verbose_name='Статус')),
                ('priority', models.PositiveSmallIntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Приоритет (1-5)')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_assignments_given', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.task', verbose_name='Задание')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Назначение задания',
                'verbose_name_plural': 'Назначения заданий',
            },
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, verbose_name='Ответ')),
                ('file', models.FileField(blank=True, null=True, upload_to='task_submissions/', verbose_name='Файл')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
                ('status', models.CharField(choices=[('SUBMITTED', 'Отправлено'), ('NEEDS_CHANGES', 'Нужны правки'), ('APPROVED', 'Принято')], default='SUBMITTED', max_length=20, verbose_name='Статус')),
                ('score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проверки')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='courses.taskassignment', verbose_name='Назначение')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Проверил')),
            ],
            options={
                'verbose_name': 'Сдача задания',
                'verbose_name_plural': 'Сдачи заданий',
            },
        ),
        migrations.CreateModel(
            name='ProgramCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательный')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='courses.course', verbose_name='Курс')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_courses', to='courses.learningprogram', verbose_name='Программа')),
            ],
            options={
                'verbose_name': 'Курс в программе',
                'verbose_name_plural': 'Курсы в программе',
                'ordering': ['order', 'id'],
                'unique_together': {('program', 'course')},
            },
        ),
        migrations.CreateModel(
            name='ProgramEnrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата назначения')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Срок прохождения')),
                ('status', models.CharField(choices=[('ASSIGNED', 'Назначена'), ('IN_PROGRESS', 'В процессе'), ('COMPLETED', 'Завершена'), ('OVERDUE', 'Просрочена'), ('CANCELLED', 'Отменена')], default='ASSIGNED', max_length=20, verbose_name='Статус')),
                ('progress', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Прогресс (%)')),
                ('completed', models.BooleanField(default=False, verbose_name='Завершена')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата завершения')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='program_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Назначил')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='courses.learningprogram', verbose_name='Программа')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='program_enrollments', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Запись на программу',
                'verbose_name_plural': 'Записи на программы',
                'unique_together': {('user', 'program')},
            },
        ),
    ]
