from django.urls import path
from .views import register_view
from .views import (
    home_view,
    redirect_after_login,
    profile_view,
    admin_panel_view,
    manager_dashboard,
    manager_course_list,
    manager_course_detail,
    manager_task_list,
    manager_lesson_list,
    manager_lesson_builder,
    manager_lesson_delete,
    manager_lesson_asset_upload,
    manager_test_quick_create,
    manager_test_quick_question,
    manager_material_list,
    manager_material_create,
    manager_material_edit,
    manager_material_delete,
    manager_students_list,
    manager_student_detail,
    manager_drafts,
    manager_task_publish,
    manager_task_edit,
    manager_task_delete,
    manager_test_publish,
    manager_test_unpublish,
    manager_test_delete,
    manager_course_create,
    manager_course_edit,
    manager_course_delete,
    manager_course_assign,
    manager_test_create,
    manager_test_edit,
    manager_test_questions,
    manager_test_results,
    manager_test_review,
    manager_task_create,
    manager_task_assign,
    analyst_dashboard,
    analyst_export,
    employee_dashboard,
    employee_course_detail,
    employee_lesson_detail,
    employee_test_decline,
    employee_test_accept,
    employee_test_take,
    employee_test_result,
    employee_task_detail,
)

urlpatterns = [
    path('', home_view, name='home'),       
    path('redirect/', redirect_after_login, name='redirect_after_login'),
    path('profile/', profile_view, name='profile'),
    path('admin-panel/', admin_panel_view, name='admin_panel'),
    path('manager/', manager_dashboard, name='manager_dashboard'),
    path('manager/courses/', manager_course_list, name='manager_course_list'),
    path('manager/courses/<int:course_id>/', manager_course_detail, name='manager_course_detail'),
    path('manager/tasks/', manager_task_list, name='manager_task_list'),
    path('manager/lessons/', manager_lesson_list, name='manager_lesson_list'),
    path('manager/lessons/create/', manager_lesson_builder, name='manager_lesson_create'),
    path('manager/lessons/<int:lesson_id>/edit/', manager_lesson_builder, name='manager_lesson_edit'),
    path('manager/lessons/<int:lesson_id>/delete/', manager_lesson_delete, name='manager_lesson_delete'),
    path('manager/lessons/asset-upload/', manager_lesson_asset_upload, name='manager_lesson_asset_upload'),
    path('manager/tests/quick-create/', manager_test_quick_create, name='manager_test_quick_create'),
    path('manager/tests/quick-question/', manager_test_quick_question, name='manager_test_quick_question'),
    path('manager/materials/', manager_material_list, name='manager_material_list'),
    path('manager/materials/create/', manager_material_create, name='manager_material_create'),
    path('manager/materials/<int:material_id>/edit/', manager_material_edit, name='manager_material_edit'),
    path('manager/materials/<int:material_id>/delete/', manager_material_delete, name='manager_material_delete'),
    path('manager/students/', manager_students_list, name='manager_students_list'),
    path('manager/students/<int:student_id>/', manager_student_detail, name='manager_student_detail'),
    path('manager/drafts/', manager_drafts, name='manager_drafts'),
    path('manager/tasks/<int:task_id>/publish/', manager_task_publish, name='manager_task_publish'),
    path('manager/tasks/<int:task_id>/edit/', manager_task_edit, name='manager_task_edit'),
    path('manager/tasks/<int:task_id>/delete/', manager_task_delete, name='manager_task_delete'),
    path('manager/tests/<int:test_id>/publish/', manager_test_publish, name='manager_test_publish'),
    path('manager/tests/<int:test_id>/unpublish/', manager_test_unpublish, name='manager_test_unpublish'),
    path('manager/tests/<int:test_id>/delete/', manager_test_delete, name='manager_test_delete'),
    path('manager/courses/create/', manager_course_create, name='manager_course_create'),
    path('manager/courses/<int:course_id>/edit/', manager_course_edit, name='manager_course_edit'),
    path('manager/courses/<int:course_id>/delete/', manager_course_delete, name='manager_course_delete'),
    path('manager/courses/<int:course_id>/assign/', manager_course_assign, name='manager_course_assign'),
    path('manager/tests/create/', manager_test_create, name='manager_test_create'),
    path('manager/tests/<int:test_id>/edit/', manager_test_edit, name='manager_test_edit'),
    path('manager/tests/<int:test_id>/questions/', manager_test_questions, name='manager_test_questions'),
    path('manager/tests/<int:test_id>/results/', manager_test_results, name='manager_test_results'),
    path('manager/tests/results/<int:result_id>/', manager_test_review, name='manager_test_review'),
    path('manager/tasks/create/', manager_task_create, name='manager_task_create'),
    path('manager/tasks/<int:task_id>/assign/', manager_task_assign, name='manager_task_assign'),
    path('analytics/', analyst_dashboard, name='analyst_dashboard'),
    path('analytics/export/<str:export_format>/', analyst_export, name='analyst_export'),
    path('employee/', employee_dashboard, name='employee_dashboard'),
    path('employee/courses/<int:course_id>/', employee_course_detail, name='employee_course_detail'),
    path('employee/lessons/<int:lesson_id>/', employee_lesson_detail, name='employee_lesson_detail'),
    path('employee/tests/<int:test_id>/decline/', employee_test_decline, name='employee_test_decline'),
    path('employee/tests/<int:test_id>/accept/', employee_test_accept, name='employee_test_accept'),
    path('employee/tests/<int:test_id>/take/', employee_test_take, name='employee_test_take'),
    path('employee/tests/results/<int:result_id>/', employee_test_result, name='employee_test_result'),
    path('employee/tasks/<int:task_id>/', employee_task_detail, name='employee_task_detail'),
    path('register/', register_view, name='register'),
]

