# Generated by Django 5.2.4 on 2026-02-03 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_created_at_test_created_by_test_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_images/', verbose_name='Изображение'),
        ),
        migrations.AddField(
            model_name='test',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок прохождения'),
        ),
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='Опубликован'),
        ),
    ]
