# Generated by Django 6.0.1 on 2026-02-09 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_test_evaluation_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='show_correct_answers',
            field=models.BooleanField(default=False, verbose_name='Показывать правильные ответы после проверки'),
        ),
        migrations.AddField(
            model_name='test',
            name='retake_requires_new_attempt',
            field=models.BooleanField(default=True, verbose_name='Пересдача тратит попытку'),
        ),
    ]
