# Generated by Django 6.0.1 on 2026-02-10 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_merge_0008_question_filefield_0008_test_attempts_thresholds_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='type',
            field=models.CharField(
                choices=[
                    ('SINGLE', 'Вопрос-ответ (один вариант)'),
                    ('MULTI', 'Вопрос-ответ (несколько вариантов)'),
                    ('MATCHING', 'Сопоставление'),
                    ('ORDERING', 'Последовательность'),
                    ('SHORT', 'Краткий ответ'),
                    ('LONG', 'Развернутый ответ'),
                ],
                default='SINGLE',
                max_length=20,
                verbose_name='Тип вопроса',
            ),
        ),
        migrations.CreateModel(
            name='MatchingPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_text', models.CharField(max_length=255, verbose_name='Левая часть')),
                ('right_text', models.CharField(max_length=255, verbose_name='Правая часть')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='matching_pairs',
                        to='tests.question',
                        verbose_name='Вопрос',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пара сопоставления',
                'verbose_name_plural': 'Пары сопоставления',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255, verbose_name='Элемент')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Правильная позиция')),
                (
                    'question',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='ordering_items',
                        to='tests.question',
                        verbose_name='Вопрос',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Элемент последовательности',
                'verbose_name_plural': 'Элементы последовательности',
                'ordering': ['position', 'id'],
            },
        ),
    ]
