# Generated by Django 5.2.4 on 2026-02-15 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_question_types_and_pairs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Попытки'),
        ),
    ]
